# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='\u7535\u5b50\u90ae\u7bb1')),
                ('password', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('phone', models.CharField(max_length=50, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
            ],
        ),
    ]
